import React, { useEffect, useState } from 'react';
import DesktopView from '@/Components/editor/Desktop/DesktopView';
import MobileView from '@/Components/editor/Mobile/MobileView';
import { useSelector, useDispatch } from 'react-redux';
import { removeValues } from '@/Components/Context/editorRedux';
import Head from 'next/head';
import { ToastContainer, toast } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

const editor = () => {
  const { color, size, gender } = useSelector((state) => state.currentProduct);

  const [windowWidth, setWindowWidth] = useState(false);

  const dispatch = useDispatch();

  useEffect(() => {
    dispatch(removeValues());
  }, []);

  useEffect(() => {
    window.addEventListener('resize', () => {
      if (window.innerWidth < 1279) {
        setWindowWidth(true);
      } else {
        setWindowWidth(false);
      }
    });
  }, []);

  return (
    <div>
      <Head>
        <title>BuzzMall.co - Editor Proizvoda</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/HomePage/favicon.png' />
      </Head>
      <ToastContainer />
      {!windowWidth ? (
        <DesktopView
          meshColor={color ? color : undefined}
          size={size}
          gender={gender}
        />
      ) : (
        <MobileView />
      )}
    </div>
  );
};

export default editor;
