import dynamic from 'next/dynamic';
import { Suspense, useRef, useState, useEffect } from 'react';
import Button from '@/Components/Button';
import Header from '@/Components/Header';
import Head from 'next/head';
import { PerspectiveCamera, Center } from '@react-three/drei';
import M from '@/Components/three/M';
import section2Img from '../public/HomePage/2section.png';
import Link from 'next/link';
import Slider from 'react-slick';
import 'slick-carousel/slick/slick.css';
import 'slick-carousel/slick/slick-theme.css';
import KeyLight from '../Components/three/KeyLight';
// import productsImageMajca from '../public/HomePage/products4.png';
import starImage from '../public/star.svg';
import slideArrow from '../public/sliderArrow.svg';
import Footer from '@/Components/Footer';
import image from '../public/rightArrow.svg';
import ScrollBar from '@/Components/ScrollBar';
import Card from '@/Components/Card';
import axios from 'axios';
import { useDispatch } from 'react-redux';
import { removeChanges } from '@/Components/Context/currentRedux';
import { useRouter } from 'next/router';
import favicon from '../public/HomePage/favicon.png';
import { url } from '@/Credentials/url';

//Web site gde korisnici mogu kupiti stvari ili napraviti dizajn
//lANDING, CARD, [ID],
//Izgled sajta kao promobox

const DynamicCanvas = dynamic(() => import('../Components/three/CanvasD'), {
  ssr: false,
});

export default function Home() {
  const [testemonialActiveSlide, setActiveSlideT] = useState(0);
  const [data, setData] = useState([]);

  const popularSliderRef = useRef();
  const testemonialSliderRef = useRef();

  const dispatch = useDispatch();
  const router = useRouter();

  useEffect(() => {
    dispatch(removeChanges());
  }, []);

  useEffect(() => {
    // axios.get('http://localhost:8800/').then((res) => setData(res.data));
    axios.get(`${url}landing`).then((res) => setData(res.data));
  }, []);

  const popularSlider = {
    slidesToShow: 2,
    slidesToScroll: 1,
    arrows: false,
    responsive: [
      {
        breakpoint: 1450,
        settings: {
          slidesToShow: 2,
        },
      },
      {
        breakpoint: 500,
        settings: {
          slidesToShow: 1,
        },
      },
    ],
  };

  const testemonialSlider = {
    className: 'center',
    centerMode: true,
    infinite: true,
    slidesToShow: 3,
    slidesToScroll: 1,
    speed: 500,
    arrows: false,
    afterChange: (next) => {
      setActiveSlideT(next);
    },
    responsive: [
      {
        breakpoint: 1023,
        settings: {
          slidesToShow: 1,
        },
      },
    ],
  };

  return (
    <>
      <Head>
        <title>BuzzMall - Home Page</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/HomePage/favicon.png' />
      </Head>
      <ScrollBar />
      <Header />
      {/* HERO */}
      <div className='flex justify-end relative'>
        <div className='bg-primary w-[87%] pt-[230px] pb-[100px] flex px-16 2xl:w-full lg:px-6 lg:pt-[150px]'>
          <div className='flex-1'>
            <div className='w-[650px] 2xl:w-[600px] lg:w-[500px] sm:w-full'>
              <h1 className='nunito font-[900] italic text-[67px] capitalize 2xl:text-[59px] lg:text-[48px] sm:text-[33px] sm:mb-12'>
                Napravi svoj dizajn <br /> proizvoda <br /> sada.
              </h1>
              <div className='flex justify-end'>
                <div>
                  <div className='mt-10 mb-6'>
                    <Button
                      text='Izaberi Proizvod'
                      bck='bg-[#EAE6DB]'
                      onClick={() => {
                        router.push('/proizvodi');
                      }}
                    />
                  </div>
                  {/* <p className='montserrat capitalize text-red-500 font-[600] text-[14px]'>
                    30% popusta na prvu porudbinu
                  </p> */}
                </div>
              </div>
            </div>
          </div>
          <div>
            {/* <div className='hidden lg:block md:hidden'>Nice</div> */}
            <div className='w-[800px] h-[650px] left-0 bottom-0 3xl:w-[700px] 3xl:h-[500px] 3xl:flex-1 xl:w-[600px] xl:h-[450px] lg:hidden'>
              <DynamicCanvas>
                <Suspense>
                  <ambientLight intensity={0.5} />
                  <KeyLight position={[-2, 0, 25]} />
                  <Center>
                    <M
                      path='./indexMesh/M.glb'
                      scale={[0.7, 0.7, 0.7]}
                      rotation={[0.2, 0, 0]}
                    />
                  </Center>
                  <PerspectiveCamera makeDefault position={[0, 0, 55]} />
                </Suspense>
              </DynamicCanvas>
            </div>
          </div>
        </div>
        {/* <div className='absolute bottom-0 left-0 bg-white px-36 py-3 2xl:px-24 lg:right-0 lg:left-auto md:hidden'> */}
        <div className='absolute bottom-0 left-0 bg-white w-[400px] h-[50px] py-3 2xl:px-24 lg:right-0 lg:left-auto md:hidden'>
          {/* <h1 className='capitalize nunito italic font-[900] text-[28px] 3xl:text-[25px] 2xl:text-[21px] flex gap-2'>
            #1
            <div>
              <span className='nunito'>online</span>
              <span className='nunito text-border block'>dizajner</span>
            </div>
          </h1> */}
        </div>
      </div>

      {/* 2SECTION */}
      {/* <div className='relative my-[200px] after:absolute after:right-0 after:top-0 after:w-1/2 after:h-full after:bg-primary lg:after:hidden lg:my-[90px] md:my-[0px]'>
        <div className='w1 flex py-[200px] gap-10 md:flex-col sm:py-[100px]'>
          <div className='flex-1'>
            <div className='mb-10'>
              <h1 className='text-[30px] montserrat font-[900] lg:text-[26px] sm:text-[22px]'>
                Print Solution 360 kao 3 u 1
              </h1>
              <p className='text-[15px] my-5 lg:text-[13px]'>
                Nas cilj je da vam omogucimo da do svojih proizvoda dodjete na
                brz i lak nacin. Omogucavamo vam da dizajnirate svoje zeljene
                proizvode na nacin kakav do sada niste imali.
              </p>
              <p className='text-[15px] lg:text-[13px] my-5'>
                Print Solution 360 vam sluzi kao prodavnica, stamparija i
                fotokopirnica u isto vreme u zavisnosti od toga sta vam je
                potrebno. Sve to bez poziva, pisanja ili odlaska iz vaseg doma.{' '}
                <span className='font-[900] lg:text-[13px]'>
                  Dizajniraj i Poruci!
                </span>
              </p>
            </div>
            <div>
              <h1 className='text-[25px] montserrat font-[600] lg:text-[21px] sm:text-[19px]'>
                Online Dizjaner
              </h1>
              <p className='text-[15px] my-5 lg:text-[13px]'>
                Print Solution 360 Online Dizajner je 3d softver koji vam
                omogucava da izaberete svoj proizvod i dizajnirate ga na nacin
                kakav vi zelite iz svih mogucih uglova i detalja.
              </p>
            </div>
            <Button
              text='Pronadji Svoj Prvi Proizvod'
              bck='bg-[#fff]'
              onClick={() => {
                router.push('/proizvodi');
              }}
            />
          </div>
          <div className='flex-1 flex flex-col items-center justify-center relative z-[2] md:mt-20'>
            <img
              className='w-[600px] h-auto md:w-[65%] sm:w-full'
              src={section2Img.src}
            />
          </div>
        </div>
      </div> */}

      {/* POPULAR PRODUCTS */}
      <div className='my-[200px] sm:my-[100px]'>
        <div className='w1'>
          <div className='flex justify-between md:flex-col mb-14'>
            <h2 className='montserrat text-[23px] montserrat font-[900] lg:text-[18px] sm:text-[17px]'>
              Proizvodi
            </h2>
            <Link
              className='capitalize underline montserrat font-[700] text-[15px] flex justify-end md:mt-5 sm:text-[13px] items-center'
              href='/proizvodi'
            >
              pogledaj sve proizvode
              <img className='ml-3 w-[20px]' src={image.src} />
            </Link>
          </div>
          <div>
            <Slider ref={popularSliderRef} {...popularSlider}>
              {/* {data.map((e, index) => {
                return <Card key={index} data={e} />;
              })} */}
            </Slider>
            {/* <div className='flex gap-7 mt-10'>
              <div
                onClick={() => {
                  if (popularSliderRef.current) {
                    popularSliderRef.current.slickPrev();
                  }
                }}
                className='border border-black p-3 cursor-pointer'
              >
                <img className='w-[20px]' src={slideArrow.src} />
              </div>
              <div
                onClick={() => {
                  if (popularSliderRef.current) {
                    popularSliderRef.current.slickNext();
                  }
                }}
                className='border border-black p-3 cursor-pointer'
              >
                <img
                  className='rotate-[180deg] w-[20px]'
                  src={slideArrow.src}
                />
              </div>
            </div> */}
          </div>
        </div>
      </div>

      {/* Testemonial */}
      {/* <div className='bg-primary pt-28 pb-48 relative'>
        <div className='triangle'></div>
        <div className='w1'>
          <h2 className='text-center montserrat font-[900] text-[23px] mb-5 md:text-[20px]'>
            Neki od nasih korisnika su odlucili da podele <br /> svoje iskustvo
          </h2>
          <div>
            <Slider ref={testemonialSliderRef} {...testemonialSlider}>
              {testemonialText.map((e, index) => {
                return (
                  <div
                    key={index}
                    className={`bg-white relative py-5 px-8  ${
                      testemonialActiveSlide == e.id
                        ? 'rounded-none after:w-[40px] after:h-[40px] after:absolute after:right-[-10px] after:top-[-10px] after:border-r-2 after:border-t-2 after:border-white before:w-[40px] before:h-[40px] before:absolute before:left-[-10px] before:bottom-[-10px] before:border-l-2 before:border-b-2 before:border-white h-[250px] !w-[500px] !inline-flex justify-center  flex-col 3xl:!w-[400px] xl:!w-[350px] lg:!w-full md:!h-auto'
                        : 'rounded-md'
                    }`}
                  >
                    <h3
                      className={`font-[900] montserrat ${
                        testemonialActiveSlide == e.id
                          ? 'text-[18px] font-[700] md:text-[16px]'
                          : 'text-[15px] font-[300]'
                      }`}
                    >
                      {e.from}
                    </h3>
                    <div className='flex items-center text-[10px] font-[100] gap-2 mb-4 mt-1'>
                      <div className='w-[8px] h-[8px] bg-green-500 rounded-full'></div>
                      Aktivan korisnik
                    </div>
                    <p
                      className={`${
                        testemonialActiveSlide == e.id
                          ? 'text-[14px] md:text-[12px]'
                          : 'text-[10px]'
                      }`}
                    >
                      {e.text}
                    </p>
                    <div
                      className={`${
                        testemonialActiveSlide == e.id
                          ? 'flex gap-1 mt-5'
                          : 'hidden'
                      }`}
                    >
                      <img
                        className='w-[20px] md:w-[16px]'
                        src={starImage.src}
                      />
                      <img
                        className='w-[20px] md:w-[16px]'
                        src={starImage.src}
                      />
                      <img
                        className='w-[20px] md:w-[16px]'
                        src={starImage.src}
                      />
                      <img
                        className='w-[20px] md:w-[16px]'
                        src={starImage.src}
                      />
                      <img
                        className='w-[20px] md:w-[16px]'
                        src={starImage.src}
                      />
                    </div>
                  </div>
                );
              })}
            </Slider>
            <div className='flex gap-2 items-center justify-center'>
              <img
                onClick={() => {
                  if (testemonialSliderRef.current) {
                    testemonialSliderRef.current.slickPrev();
                  }
                }}
                className='w-[20px]'
                src={slideArrow.src}
              />
              {testemonialText.map((e) => {
                return (
                  <div
                    className={`rounded-full  w-[7px] h-[7px] ${
                      testemonialActiveSlide == e.id
                        ? 'bg-black'
                        : 'bg-slate-100'
                    }`}
                  ></div>
                );
              })}
              <img
                onClick={() => {
                  if (testemonialSliderRef.current) {
                    testemonialSliderRef.current.slickNext();
                  }
                }}
                className='rotate-[180deg] w-[20px]'
                src={slideArrow.src}
              />
            </div>
          </div>
        </div>
      </div> */}
      <Footer />
    </>
  );
}
